/* PRODUCTS */
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_ALL_RELEASES = "GET_ALL_RELEASES";
export const GET_ALL_RELEASES_BY_ID = "GET_ALL_RELEASES_BY_ID";
export const GET_ALL_DOCUMENTS = "GET_ALL_DOCUMENTS";
export const GET_ALL_DOCUMENTS_BY_RELEASE_ID = "GET_ALL_DOCUMENTS_BY_RELEASE_ID";

export const GET_ALL_DATA = "GET_ALL_DATA";